name: "Docker Action sample"
author: "yuichielectric"
description: "Sample Docker Action"
inputs:
  secret:
    description: Secret
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - --build-arg SECRET=${{ inputs.secret }}
  env:
    SECRET: ${{ inputs.secret }}
